var Application, app, dev, fs, prod, publicPath, templatesPath;
Application = require('stick').Application;
fs = require('fs');
publicPath = module.resolve(fs.join('..', 'public'));
templatesPath = module.resolve(fs.join('..', 'templates'));
app = exports.app = Application();
app.configure('notfound', 'params', 'route', 'render');
dev = app.env('dev');
dev.configure('static', 'error');
dev.static(publicPath);
prod = app.env('production');
prod.configure('gzip', 'etag', 'static', 'error');
prod.error.location = false;
prod.static(publicPath);
app.render.base = templatesPath;
app.render.master = 'page.html';